name: GitHub Actions Run Pytest
on: [push]
jobs:
  Run-Pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest on repo
        run: pytest
      - run: echo "🍏 This job's status is ${{ job.status }}."
